version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fishing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fishing
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    build: ./web
    command: python app.py
    volumes:
      - ./web:/app
    environment:
      API_URL: http://api:8000
    ports:
      - "5000:5000"
    depends_on:
      - api

volumes:
  postgres_data:

